name: google_map_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state managment
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

  # place .env key 
  flutter_dotenv: ^5.1.0

  # map 
  google_maps_flutter: ^2.5.0

  #location service
  location: ^5.0.3

  # handle permissions
  permission_handler: ^11.0.0
  flutter_google_places_sdk: ^0.3.5
  flutter_polyline_points: ^2.0.0
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/markers/
    - assets/svg/
